// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkK6xgB2MdRnxydVO1UbQTB5XaZSB1pig',
    appId: '1:413939469948:android:b91eb72f8b07cb1674c3f9',
    messagingSenderId: '413939469948',
    projectId: 'sri-sakthivel-fireworks-pos',
    storageBucket: 'sri-sakthivel-fireworks-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD0G2uBstJ85h7TTgg4ySxFAoVcsi2Pzc',
    appId: '1:413939469948:ios:a0f1a45ae28cc5bd74c3f9',
    messagingSenderId: '413939469948',
    projectId: 'sri-sakthivel-fireworks-pos',
    storageBucket: 'sri-sakthivel-fireworks-pos.appspot.com',
    iosClientId: '413939469948-h0lb1pttir7o50b46kh4o8krhdqik6jb.apps.googleusercontent.com',
    iosBundleId: 'com.srisoftwarez.sriSakthivelFireworksPos',
  );
}
